#pragma once

#define EE_HANDS
#define SPLIT_USB_DETECT
#define SPLIT_MAX_CONNECTION_ERRORS 10
#define SPLIT_CONNECTION_CHECK_TIMEOUT 500
#define SPLIT_TRANSPORT_MIRROR

#define TAPPING_TERM 175
#define DEBOUNCE 5
#define ENCODER_RESOLUTION 4

#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 0
